name: disable_battery_optimization_example
description: Demonstrates how to use the disable_battery_optimization plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  disable_battery_optimization:
    path: ../

flutter:
  uses-material-design: true